Initial version of CI pipeline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,7 +1,4 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
-
-name: "Smartmirror.one CI"
+name: Smartmirror.one CI
 
 on:
   push:
@@ -10,21 +7,115 @@ on:
     branches: [ main ]
 
 jobs:
-  build:
 
+  lint-test-build:
+    name: Lint, Test and Build
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        node-version: [16.x]
 
     steps:
     - uses: actions/checkout@v3
-    - name: Use Node.js ${{ matrix.node-version }}
+
+    - name: Setup Node.js Dependencies
       uses: actions/setup-node@v3
       with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - run: npm run build
-    - run: npm test
+        node-version: 16.x
+        cache: npm
+
+    - name: Install Project Dependencies
+      run: npm ci
+
+    - name: Lint Packages
+      run: npm run lint
+
+    - name: Test Packages
+      run: npm test
+
+    - name: Test Report - Backend
+      uses: dorny/test-reporter@v1
+      if: success() || failure() # run this step even if previous step failed
+      with:
+        name: Backend Jest Tests
+        path: packages/backend/junit.xml
+        reporter: jest-junit
+
+    - name: Build Packages
+      run: npm run build
+
+    - name: Archive Build Artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: build-result
+        path: packages/**/dist
+
+    - name: Comment Code Coverage Results on PR
+      if: github.event_name == 'pull_request'
+      uses: ArtiomTr/jest-coverage-report-action@v2
+      with:
+        coverage-file: packages/backend/coverage/coverage-final.json
+        base-coverage-file: packages/backend/coverage/coverage-final.json
+
+  package:
+    name: Package Binaries
+    runs-on: ${{ matrix.os }}
+    if: github.event_name != 'pull_request'
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, macOS-latest, windows-latest]
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: Setup Node.js Dependencies
+      uses: actions/setup-node@v3
+      with:
+        node-version: 16.x
+        cache: npm
+
+    - name: Install Project Dependencies
+      run: npm ci
+
+    - name: Download Build Artifacts
+      uses: actions/download-artifact@v3
+      with:
+        name: build-result
+
+    - run: ls -R
+
+    - name: Generate Binary
+      run: npm run update-public && npm run package
+      working-directory: packages/backend
+
+    - name: Upload Binary for Release
+      uses: actions/upload-artifact@v2
+      with:
+        name: release
+        path: packages/backend/_bins/*
+
+  release:
+    name: Release Version
+    runs-on: ubuntu-latest
+    if: github.event_name != 'pull_request'
+    
+    steps:
+
+    - name: Download Release Binaries
+      uses: actions/download-artifact@v3
+      with:
+        name: build-result
+        path: releases
+
+    - run: ls -R
+
+    - name: Release Binaries to GitHub
+      uses: meeDamian/github-release@2.0
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        name: Smartmirror.one
+        allow_override: true
+        draft: true
+        prerelease: true
+        files: >
+          smartmirror-one-v1.0.0-linux:releases/smartmirror1-linux
+          smartmirror-one-v1.0.0-mac:releases/smartmirror1-darwin
+          smartmirror-one-v1.0.0-windows:releases/smartmirror1-win32.exe
